language: php

php:
  - 8.2

env:
  - DB_CONNECTION=sqlite
    DB_DATABASE=:memory:

install:
  - cp .env.example .env
  - composer install --no-interaction --prefer-dist
  - php artisan key:generate

before_script:
  - php artisan migrate --force

script:
  - php artisan test
